# Generated by Django 3.2.5 on 2022-03-31 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usernameAccount', models.CharField(max_length=128, unique=True)),
                ('emailAccount', models.EmailField(max_length=128, unique=True)),
                ('evaluation', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'user_datas',
            },
        ),
        migrations.CreateModel(
            name='FundingProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nftId', models.PositiveIntegerField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('token', models.CharField(max_length=18)),
                ('buyPrice', models.DecimalField(decimal_places=18, max_digits=18)),
                ('sellPrice', models.DecimalField(decimal_places=18, max_digits=18)),
                ('gasPrice', models.DecimalField(decimal_places=18, max_digits=18)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funding_projects',
            },
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletType', models.CharField(max_length=18)),
                ('walletAddress', models.CharField(max_length=36)),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_address',
            },
        ),
        migrations.CreateModel(
            name='TransferLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAddress', models.CharField(max_length=36)),
                ('toAddress', models.CharField(max_length=36)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=18)),
                ('token', models.CharField(max_length=18)),
                ('time', models.DateTimeField()),
                ('transferCheck', models.BooleanField(default=False)),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfer_logs',
            },
        ),
        migrations.CreateModel(
            name='LikeLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundingProject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mydatabase.fundingprojects')),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like_lists',
            },
        ),
        migrations.CreateModel(
            name='FundingShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=18, max_digits=18)),
                ('fundingProject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mydatabase.fundingprojects')),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funding_shares',
            },
        ),
        migrations.AddField(
            model_name='fundingprojects',
            name='userFundingShare',
            field=models.ManyToManyField(related_name='userFunding', through='mydatabase.FundingShares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingprojects',
            name='userLikeList',
            field=models.ManyToManyField(related_name='userLike', through='mydatabase.LikeLists', to=settings.AUTH_USER_MODEL),
        ),
    ]
